Repository ScorpioStation/ScorpioStation, pull requests merged in 2020-07, with the labels that each got.

#81 Removes Antag Greentext
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/heist/heist.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/gamemodes/vampire/vampire.dm
  code/game/gamemodes/wizard/wizard.dm
Labels: Feature

#86 Ports runechat from SS220
  SQL/paradise_schema.sql
  SQL/paradise_schema_prefixed.sql
  SQL/updates/runechat.sql
  code/__DEFINES/layers.dm
  code/__HELPERS/lists.dm
  code/datums/chatmessage.dm
  code/game/atoms.dm
  code/modules/client/client defines.dm
  code/modules/client/preference/preferences.dm
  code/modules/client/preference/preferences_mysql.dm
  code/modules/mob/hear_say.dm
  icons/effects/chat_icons.dmi
  interface/skin.dmf
  paradise.dme
Labels: SQL

#96 Fixes the ArkSoft hoodie inventory icon as well as the Ark Soft poster being called Nanotrasen.
  _maps/map_files/Delta/delta.dmm
  _maps/map_files/RandomRuins/SpaceRuins/oldstation.dmm
  _maps/map_files/RandomZLevels/moonoutpost19.dmm
  _maps/map_files/RandomZLevels/terrorspiders.dmm
  _maps/map_files/RandomZLevels/undergroundoutpost45.dmm
  code/game/objects/effects/decals/contraband.dm
  icons/obj/clothing/suits.dmi
Labels: Fix, Sprites

#91 Ports runechat from SS220 - Attempt #2
  SQL/paradise_schema.sql
  SQL/paradise_schema_prefixed.sql
  SQL/updates/runechat.sql
  code/__DEFINES/layers.dm
  code/__HELPERS/lists.dm
  code/datums/chatmessage.dm
  code/game/atoms.dm
  code/game/objects/items/devices/megaphone.dm
  code/modules/client/client defines.dm
  code/modules/client/preference/preferences.dm
  code/modules/client/preference/preferences_mysql.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/say.dm
  icons/effects/chat_icons.dmi
  interface/skin.dmf
  paradise.dme
Labels: SQL

#103 Makes sure Ark Rep is command, and removes old NT rep being command
  code/game/machinery/tcomms/nttc.dm
Labels: Fix

#107 Slightly less annoying addictions
  code/modules/reagents/chemistry/reagents/drugs.dm
  code/modules/reagents/chemistry/reagents/medicine.dm
Labels: Tweak

#133 Immolator description spelling fix.
  code/modules/projectiles/guns/energy/laser.dm
Labels: Fix

#134 Small grammar error fix in SMES announcement
  code/modules/events/apc_short.dm
Labels: Fix

#84 Adds Ark Soft Instructor job for Mentors
  code/game/jobs/access.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/support.dm
  code/game/jobs/jobs.dm
  code/game/machinery/computer/card.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/weapons/manuals.dm
  code/modules/client/preference/preferences.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/modular_computers/file_system/programs/command/card.dm
Labels: Feature

#85 Ghosts can spawn from diona nymph pods
  code/modules/hydroponics/grown/nymph.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/hydroponics/seeds.dm
Labels: QoL

#124 Ambulance Update
  code/modules/vehicle/ambulance.dm
Labels: Balance, Fix

#135 Slow down robots, Speed up animals
  config/example/game_options.txt
Labels: Tweak

#130 Purge of the cluwnes
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/spawnfloorcluwne.dm
  code/modules/events/event_container.dm
  code/modules/events/floorcluwne.dm
  code/modules/mob/living/simple_animal/hostile/floorcluwne.dm
  paradise.dme
Labels: Balance, Revert

#128 Gamemode Selection
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/blob/blob.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/extended/extended.dm
  code/game/gamemodes/meteor/meteor.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/shadowling/shadowling.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/gamemodes/vampire/vampire.dm
  code/game/gamemodes/wizard/wizard.dm
Labels: Balance, Fix, Refactor

#140 Refactors gamemode setup
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/changeling/traitor_chan.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/gamemodes/vampire/traitor_vamp.dm
Labels: Refactor

#143 Add Limitless SMES command for Admins
  code/modules/admin/secrets.dm
  code/modules/admin/topic.dm
  code/modules/events/apc_short.dm
Labels: QoL

#144 Automatically turns off events below 15 players
  code/modules/events/event_container.dm
Labels: Balance, Tweak

#145 Scales Department Access to Pop and Fixes Access Rights
  code/controllers/configuration.dm
  code/controllers/subsystem/ticker.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/support.dm
  code/game/jobs/job/support_chaplain.dm
  config/example/config.txt
Labels: Balance

#141 Removes prisoner gear from normal brig lockers
  _maps/map_files/emerald/emerald.dmm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Fix
