Repository ScorpioStation/ScorpioStation, pull requests merged in 2020-06, with the labels that each got.

#38 Added box for IV bags.
  code/game/objects/items/weapons/storage/boxes.dm
  icons/obj/storage.dmi
Labels: sprites needed

#44 Added a Ark rep job icon sprite as well as a Ark Soft zippo lighter sprite
  _maps/map_files/Delta/delta.dmm
  _maps/map_files/MetaStation/MetaStation.v41A.II.dmm
  _maps/map_files/cyberiad/cyberiad.dmm
  code/datums/outfits/outfit_admin.dm
  code/game/jobs/job/supervisor.dm
  code/game/objects/items/weapons/lighters.dm
  icons/mob/hud.dmi
  icons/obj/items.dmi
Labels: Sprites

#45 Arrivals doors will now automatically close
  code/game/machinery/doors/unpowered.dm
Labels: Fix

#47 Fixes the field generator welding messages
  code/__DEFINES/tools.dm
  code/modules/power/singularity/field_generator.dm
Labels: Fix

#55 Makes the geneticist a medical only role
  _maps/map_files/MetaStation/MetaStation.v41A.II.dmm
  code/game/jobs/access.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/jobs.dm
  code/game/machinery/tcomms/nttc.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/weapons/cards_ids.dm
Labels: Tweak

#50 Changed some NT Branding to Arksoft.
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/soap.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/client/preference/loadout/loadout_suit.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/suit.dmi
  icons/mob/underwear.dmi
  icons/obj/cardboard_boxes.dmi
  icons/obj/closet.dmi
  icons/obj/contraband.dmi
  icons/obj/items.dmi
  icons/obj/library.dmi
  icons/obj/storage.dmi
  icons/obj/toy.dmi
Labels: Merge Conflict, Sprites
