Repository ScorpioStation/ScorpioStation, pull requests merged in 2020-08, with the labels that each got.

#155 Re-adds the ark soft gold engraved zippo lighter sprite
  icons/obj/items.dmi
Labels: Fix

#156 Fixes Superhero Wishgranter
  code/game/machinery/wishgranter.dm
Labels: Fix

#161 Updates Hub Entry to be more informative
  code/game/world.dm
Labels: QoL, Tweak

#163 DMAPI Reboot
  code/game/world.dm
Labels: Fix

#168 Minor map fixes
  _maps/map_files/emerald/emerald.dmm
Labels: Fix

#170 Bunch of painting bugfixes
  code/game/objects/structures/artstuff.dm
Labels: Fix

#171 Final Painting/Displaycase Fixes
  _maps/map_files/emerald/emerald.dmm
  code/controllers/subsystem/persistance.dm
  code/game/objects/structures/artstuff.dm
  code/game/objects/structures/displaycase.dm
Labels: Fix

#172 Alarm and display case fixes
  code/game/objects/structures/artstuff.dm
  code/game/objects/structures/displaycase.dm
Labels: Balance, Fix

#174 Adds a bunch of cockroach content
  _maps/map_files/emerald/emerald.dmm
  code/modules/food_and_drinks/food/foods/sandwiches.dm
  code/modules/food_and_drinks/recipes/recipes_microwave.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/simple_animal/friendly/cockroach.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/mutant_cockroach.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/retaliate.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  icons/mob/animal.dmi
  icons/obj/food/food.dmi
  paradise.dme
  sound/creatures/roach_hiss1.ogg
  sound/creatures/roach_hiss2.ogg
  sound/creatures/roach_hiss3.ogg
Labels: Feature, Sprites, bug

#175 Limits cockroach hiss chat message spam
  code/modules/mob/living/simple_animal/friendly/cockroach.dm
Labels: Fix

#185 Remove debug logging messages from Census subsystem
  code/controllers/subsystem/census.dm
Labels: Fix

#150 Allow heads to be put on trophy rack backpack
  code/game/objects/items/weapons/storage/backpack.dm
Labels: Feature

#187 Fix Runechat Span Bug
  code/__HELPERS/text.dm
  code/datums/chatmessage.dm
  code/game/dna/genes/disabilities.dm
Labels: Fix

#157 [TESTMERGE] Vox, Drask and Kidan changes
  code/game/atoms_movable.dm
  code/game/dna/genes/goon_disabilities.dm
  code/game/dna/genes/powers.dm
  code/modules/mob/living/carbon/human/species/drask.dm
  code/modules/mob/living/carbon/human/species/kidan.dm
  code/modules/mob/living/carbon/human/species/vox.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob_movement.dm
Labels: Balance, Feature

#189 Various Bugfixes
  code/game/objects/structures/statues.dm
  code/modules/station_goals/dna_vault.dm
Labels: Fix

#190 Adds rods to statue pedestals icons
  icons/obj/statue.dmi
Labels: Fix, Sprites

#191 Baseball update
  _maps/map_files/emerald/emerald.dmm
  code/game/machinery/baseball_machine.dm
  code/game/objects/items/weapons/weaponry.dm
  icons/obj/machines/baseball_machine.dmi
  paradise.dme
  sound/machines/baseball_machine.ogg
Labels: Feature, Sprites

#195 Gym Update
  _maps/map_files/emerald/emerald.dmm
  code/datums/status_effects/buffs.dm
  code/game/area/emerald_areas.dm
  code/game/objects/effects/decals/wrestling.dm
  code/game/turfs/simulated/floor/misc_floor.dm
  code/modules/admin/verbs/onlyoneteam.dm
  code/modules/ruins/objects_and_mobs/gym.dm
  icons/misc/wrestling_ring.dmi
  paradise.dme
Labels: Feature, Sprites

#192 Timestop rework from TG
  code/__DEFINES/misc.dm
  code/controllers/subsystem/processing/fields.dm
  code/game/objects/effects/proximity.dm
  code/modules/fields/fields.dm
  code/modules/fields/timestop.dm
  code/modules/fields/turf_objects.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  code/modules/research/xenobiology/xenobiology.dm
  paradise.dme
Labels: Fix, Refactor

#181 Lawchange Induced Synthetic Psychosis (LISP)
  code/datums/ai_law_sets.dm
  code/game/machinery/computer/law.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/laws.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/silicon.dm
  tools/scorpio/check_icon_state_manifest/icon_state.manifest
Labels: Feature

#197 8/25/20 Upstream Merge
  code/datums/outfits/outfit_admin.dm
  code/defines/vox_sounds.dm
  code/game/machinery/vending.dm
  code/game/objects/effects/spiders.dm
  code/game/verbs/ooc.dm
  code/modules/admin/topic.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/mob/living/silicon/ai/say.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/fish.dm
  goon/browserassets/css/browserOutput-dark.css
Labels: Upstream Merge

#199 Fix typo in baseball machines visible message
  code/game/machinery/baseball_machine.dm
Labels: Fix

#201 Adds an Ark Soft Icon, that is used instead of the NT one on official papers from CC
  code/__HELPERS/text.dm
  code/game/gamemodes/game_mode.dm
  code/game/objects/structures/safe.dm
  code/modules/admin/topic.dm
  code/modules/client/asset_cache.dm
  code/modules/paperwork/paper.dm
  icons/paper_icons/arksoftlogo.png
Labels: Fix, Sprites

#203 Gym fixes
  code/datums/status_effects/buffs.dm
  code/game/objects/effects/decals/wrestling.dm
Labels: Fix

#205 8/29/20 Upstream Merge
  .travis.yml
  code/_onclick/hud/alert.dm
  code/controllers/subsystem/ghost_spawns.dm
  code/datums/components/caltrop.dm
  code/datums/components/slippery.dm
  code/datums/components/squeak.dm
  code/datums/log_record.dm
  code/datums/log_viewer.dm
  code/datums/supplypacks.dm
  code/datums/weather/weather_types/floor_is_lava.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/blob/blobs/blob_mobs.dm
  code/game/gamemodes/blob/blobs/core.dm
  code/game/gamemodes/blob/powers.dm
  code/game/gamemodes/changeling/powers/swap_form.dm
  code/game/gamemodes/miniantags/guardian/guardian.dm
  code/game/gamemodes/miniantags/revenant/revenant.dm
  code/game/gamemodes/wizard/artefact.dm
  code/game/gamemodes/wizard/raginmages.dm
  code/game/machinery/recycler.dm
  code/game/objects/items/weapons/shards.dm
  code/game/objects/structures/crates_lockers/crittercrate.dm
  code/game/turfs/simulated/floor/chasm.dm
  code/game/turfs/turf.dm
  code/game/world.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/striketeam.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/suits/utility.dm
  code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
  code/modules/food_and_drinks/food.dm
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/mining/lavaland/loot/colossus_loot.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/friendly/butterfly.dm
  code/modules/mob/living/simple_animal/hostile/bat.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/undead.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/living/simple_animal/shade.dm
  code/modules/mob/living/status_procs.dm
  code/modules/mob/mob_movement.dm
  code/modules/mob/update_status.dm
  code/modules/power/lighting.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/surgery/organs/helpers.dm
  tools/send2server.py
Labels: Upstream Merge

#206 Clothing description replacement from NT to ARK
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/miscellaneous.dm
Labels: Fix

#207 Adds Arrival and Cryo Discord Webhook Integration
  code/controllers/configuration.dm
  code/controllers/subsystem/census.dm
  code/datums/discord/webhook.dm
  code/game/machinery/cryopod.dm
  code/modules/mob/living/silicon/ai/latejoin.dm
  code/modules/mob/new_player/new_player.dm
  config/example/config.txt
  paradise.dme
Labels: Feature, QoL

#209 Fix and expand Discord arrivals announcement
  code/controllers/subsystem/ticker.dm
  code/datums/discord/webhook.dm
  code/modules/mob/new_player/new_player.dm
Labels: Feature, Fix
